name: Deploy Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm ci

    - name: Setup Google Creds
      env:
        GOOGLE_CREDS: ${{ secrets.GOOGLE_CREDS }}
      run: |
        mkdir -p credentials
        echo "$GOOGLE_CREDS" | base64 --decode > credentials/service-account.json

    - name: Run Bot
      env:
        TELEGRAM_TOKEN: ${{ 7924129087:AAECLBXF9DuuTTMzAJP5JyPcJdYjpAmH4NE }}
        GOOGLE_SHEET_ID: ${{ AIzaSyBBJOusSW5G9021VRHpDBU1viB_f3NiR00 }}
      run: |
        npm start &
